/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PubsPlaceIdRouteImport } from './routes/pubs.$placeId'
import { Route as PubsPlaceIdRateRouteImport } from './routes/pubs.$placeId_.rate'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PubsPlaceIdRoute = PubsPlaceIdRouteImport.update({
  id: '/pubs/$placeId',
  path: '/pubs/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PubsPlaceIdRateRoute = PubsPlaceIdRateRouteImport.update({
  id: '/pubs/$placeId_/rate',
  path: '/pubs/$placeId/rate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pubs/$placeId': typeof PubsPlaceIdRoute
  '/pubs/$placeId/rate': typeof PubsPlaceIdRateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pubs/$placeId': typeof PubsPlaceIdRoute
  '/pubs/$placeId/rate': typeof PubsPlaceIdRateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pubs/$placeId': typeof PubsPlaceIdRoute
  '/pubs/$placeId_/rate': typeof PubsPlaceIdRateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/map'
    | '/sitemap.xml'
    | '/pubs/$placeId'
    | '/pubs/$placeId/rate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/map'
    | '/sitemap.xml'
    | '/pubs/$placeId'
    | '/pubs/$placeId/rate'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/map'
    | '/sitemap.xml'
    | '/pubs/$placeId'
    | '/pubs/$placeId_/rate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PubsPlaceIdRoute: typeof PubsPlaceIdRoute
  PubsPlaceIdRateRoute: typeof PubsPlaceIdRateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubs/$placeId': {
      id: '/pubs/$placeId'
      path: '/pubs/$placeId'
      fullPath: '/pubs/$placeId'
      preLoaderRoute: typeof PubsPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubs/$placeId_/rate': {
      id: '/pubs/$placeId_/rate'
      path: '/pubs/$placeId/rate'
      fullPath: '/pubs/$placeId/rate'
      preLoaderRoute: typeof PubsPlaceIdRateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PubsPlaceIdRoute: PubsPlaceIdRoute,
  PubsPlaceIdRateRoute: PubsPlaceIdRateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
